# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_editors'),
        ('users', '0003_auto_20170916_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='companies.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Team'),
        ),
    ]
