# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_employee'),
        ('users', '0004_auto_20171030_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
