# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171030_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='teste', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
