# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170916_1620'),
        ('companies', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to='users.User'),
        ),
    ]
