# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_question_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='time_limit',
            field=models.DateTimeField(null=True),
        ),
    ]
