# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20171021_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reversed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
